import 'package:json_annotation/json_annotation.dart';

part 'newpipe_subtitle.g.dart';

@JsonSerializable()
class NewPipeSubtitle {
  final String? url;
  final String? mimeType;
  final String? languageCode;
  final bool? autoGenerated;

  NewPipeSubtitle({
    this.url,
    this.mimeType,
    this.languageCode,
    this.autoGenerated,
  });

  factory NewPipeSubtitle.fromJson(Map<String, dynamic> json) =>
      _$NewPipeSubtitleFromJson(json);

  Map<String, dynamic> toJson() => _$NewPipeSubtitleToJson(this);
}
