// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'newpipe_subtitle.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

NewPipeSubtitle _$NewPipeSubtitleFromJson(Map<String, dynamic> json) =>
    NewPipeSubtitle(
      url: json['url'] as String?,
      mimeType: json['mimeType'] as String?,
      languageCode: json['languageCode'] as String?,
      autoGenerated: json['autoGenerated'] as bool?,
    );

Map<String, dynamic> _$NewPipeSubtitleToJson(NewPipeSubtitle instance) =>
    <String, dynamic>{
      'url': instance.url,
      'mimeType': instance.mimeType,
      'languageCode': instance.languageCode,
      'autoGenerated': instance.autoGenerated,
    };
