/// Generic subtitle model that works with all video services
class GenericSubtitle {
  final String? url;
  final String? languageCode;
  final String? name;
  final bool autoGenerated;

  GenericSubtitle({
    this.url,
    this.languageCode,
    this.name,
    this.autoGenerated = false,
  });

  /// Create from a map (Piped format)
  factory GenericSubtitle.fromMap(Map<String, String> map) {
    return GenericSubtitle(
      url: map['url'],
      languageCode: map['name']?.split(' - ').first,
      name: map['name'],
      autoGenerated: map['name']?.contains('auto') ?? false,
    );
  }
}
